name: Cesium for Unreal

# ToDo:
# 1.) Path noted is not accurate.
#      - Lets make that an environment variable for clarity.
# 2.) Try running Windows build self-hosted.
# 3.) Add MacOS & iOS builds

on: [workflow_dispatch]
jobs:
  Windows54:
    uses: ./.github/workflows/buildWindows.yml
    with:
      runner-label: "windows-2022"
      unreal-engine-version: "5.4.0"
      unreal-engine-zip-path: "${{ github.workspace }}\\..\\UnrealEngine\\UnrealEngine\\UnrealEngine.zip"
      unreal-program-name: "UE_5.4"
      upload-package-base-name: "CesiumForUnreal-54-windows"
      # These are specified in the Unreal Engine release notes under "IDE Version the Build farm compiles against"
      # and using them ensures we're compiling our plugin in the exact same way that Unreal Engine itself is compiled.
      cmake-generator: "Visual Studio 17 2022"
      cmake-toolchain: "version=14.34"
      cmake-platform: "x64,version=10.0.18362.0"
      visual-studio-version: "2022"
      visual-studio-components: "Microsoft.VisualStudio.Component.VC.14.34.17.4.x86.x64,Microsoft.VisualStudio.Component.Windows10SDK.18362"
  TestWindows54:
    needs: [Windows54]
    uses: ./.github/workflows/testWindows.yml
    secrets: inherit
    with:
      runner-label: windows-2022
      unreal-engine-zip-path: "${{ github.workspace }}\\..\\UnrealEngine\\UnrealEngine\\UnrealEngine.zip"
      unreal-program-name: "UE_5.4"
      test-package-base-name: "CesiumForUnreal-54-windows"
  Android54:
    uses: ./.github/workflows/buildAndroid.yml
    secrets: inherit
    with:
      runner-label: windows-2022
      unreal-engine-version: "5.4.0"
      unreal-engine-zip-path: "${{ github.workspace }}\\..\\UnrealEngine\\UnrealEngine\\UnrealEngine.zip"
      unreal-program-name: "UE_5.4"
      upload-package-base-name: "CesiumForUnreal-54-android"
      android-ndk-version: "r25b"
  Combine54:
    runs-on: ubuntu-latest
    needs: [Windows54, Android54]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          export CESIUM_UNREAL_VERSION=$GITHUB_REF_NAME
          export BUILD_CESIUM_UNREAL_PACKAGE_NAME="CesiumForUnreal-54-${CESIUM_UNREAL_VERSION}"
          export BUILD_CESIUM_UNREAL_SOURCE_ONLY_PACKAGE_NAME="CesiumForUnreal-54-SourceOnly-${CESIUM_UNREAL_VERSION}"
          # Make these available to subsequent steps
          echo "CESIUM_UNREAL_VERSION=$CESIUM_UNREAL_VERSION" >> $GITHUB_ENV
          echo "BUILD_CESIUM_UNREAL_PACKAGE_NAME=$BUILD_CESIUM_UNREAL_PACKAGE_NAME" >> $GITHUB_ENV
          echo "BUILD_CESIUM_UNREAL_SOURCE_ONLY_PACKAGE_NAME=$BUILD_CESIUM_UNREAL_SOURCE_ONLY_PACKAGE_NAME" >> $GITHUB_ENV
      - name: Download Android build
        uses: actions/download-artifact@v4
        with:
          name: CesiumForUnreal-54-android-${{ env.CESIUM_UNREAL_VERSION}}
          path: combine
      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: CesiumForUnreal-54-windows-${{ env.CESIUM_UNREAL_VERSION}}
          path: combine
      - name: Publish combined package artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_CESIUM_UNREAL_PACKAGE_NAME}}
          path: combine
      - name: Publish combined package artifact for the Unreal Marketplace
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_CESIUM_UNREAL_SOURCE_ONLY_PACKAGE_NAME}}
          path: |
            combine
            # These are built by Epic, and including them seems to confuse their process.
            !combine/CesiumForUnreal/Binaries/**/*
            !combine/CesiumForUnreal/Intermediate/**/*
  TestPackage54:
    needs: [Combine54]
    uses: ./.github/workflows/testPackageOnWindows.yml
    secrets: inherit
    with:
      runner-label: windows-2022
      unreal-engine-zip-path: "${{ github.workspace }}\\..\\UnrealEngine\\UnrealEngine\\UnrealEngine.zip"
      unreal-program-name: "UE_5.4"
      unreal-engine-association: "5.4"
      test-package-base-name: "CesiumForUnreal-54"
      visual-studio-version: "2022"
      visual-studio-components: "Microsoft.VisualStudio.Component.VC.14.34.17.4.x86.x64,Microsoft.VisualStudio.Component.Windows10SDK.18362"
